# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbc23d25534f6a35d13b28c1b640dbfb3a53d87a1d017b427fd5d2e5770c73db7d8505ac85bc04b4bddc0aafc8fe7f61e7810c0072d554ffd050d4e609732eee
  soundcloud_api_key: "2183d454de17f8dabc1d2e15616bc66f"
  soundcloud_secret: "f98a9170c2afdf2af6e8e04b4818eb4d"

test:
  secret_key_base: 5dfa8092ba6553d75e777aa6a06ca09ffa7dd85443342324fe42a9c212e2fdc77366fbac2e9ff2f2f9970ebb4cc819c306eb65466371e137db318d710600e16d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  soundcloud_api_key: "2183d454de17f8dabc1d2e15616bc66f"
  soundcloud_secret: "f98a9170c2afdf2af6e8e04b4818eb4d"